USE [master]
GO
/****** Object:  Database [WPFTask]    Script Date: 4/12/2025 10:21:33 PM ******/
CREATE DATABASE [WPFTask]
 CONTAINMENT = NONE
 ON  PRIMARY 
( NAME = N'WPFTask', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL15.MSSQLSERVER\MSSQL\DATA\WPFTask.mdf' , SIZE = 8192KB , MAXSIZE = UNLIMITED, FILEGROWTH = 65536KB )
 LOG ON 
( NAME = N'WPFTask_log', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL15.MSSQLSERVER\MSSQL\DATA\WPFTask_log.ldf' , SIZE = 73728KB , MAXSIZE = 2048GB , FILEGROWTH = 65536KB )
 WITH CATALOG_COLLATION = DATABASE_DEFAULT
GO
ALTER DATABASE [WPFTask] SET COMPATIBILITY_LEVEL = 150
GO
IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [WPFTask].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO
ALTER DATABASE [WPFTask] SET ANSI_NULL_DEFAULT OFF 
GO
ALTER DATABASE [WPFTask] SET ANSI_NULLS OFF 
GO
ALTER DATABASE [WPFTask] SET ANSI_PADDING OFF 
GO
ALTER DATABASE [WPFTask] SET ANSI_WARNINGS OFF 
GO
ALTER DATABASE [WPFTask] SET ARITHABORT OFF 
GO
ALTER DATABASE [WPFTask] SET AUTO_CLOSE OFF 
GO
ALTER DATABASE [WPFTask] SET AUTO_SHRINK OFF 
GO
ALTER DATABASE [WPFTask] SET AUTO_UPDATE_STATISTICS ON 
GO
ALTER DATABASE [WPFTask] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO
ALTER DATABASE [WPFTask] SET CURSOR_DEFAULT  GLOBAL 
GO
ALTER DATABASE [WPFTask] SET CONCAT_NULL_YIELDS_NULL OFF 
GO
ALTER DATABASE [WPFTask] SET NUMERIC_ROUNDABORT OFF 
GO
ALTER DATABASE [WPFTask] SET QUOTED_IDENTIFIER OFF 
GO
ALTER DATABASE [WPFTask] SET RECURSIVE_TRIGGERS OFF 
GO
ALTER DATABASE [WPFTask] SET  DISABLE_BROKER 
GO
ALTER DATABASE [WPFTask] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO
ALTER DATABASE [WPFTask] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO
ALTER DATABASE [WPFTask] SET TRUSTWORTHY OFF 
GO
ALTER DATABASE [WPFTask] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO
ALTER DATABASE [WPFTask] SET PARAMETERIZATION SIMPLE 
GO
ALTER DATABASE [WPFTask] SET READ_COMMITTED_SNAPSHOT OFF 
GO
ALTER DATABASE [WPFTask] SET HONOR_BROKER_PRIORITY OFF 
GO
ALTER DATABASE [WPFTask] SET RECOVERY FULL 
GO
ALTER DATABASE [WPFTask] SET  MULTI_USER 
GO
ALTER DATABASE [WPFTask] SET PAGE_VERIFY CHECKSUM  
GO
ALTER DATABASE [WPFTask] SET DB_CHAINING OFF 
GO
ALTER DATABASE [WPFTask] SET FILESTREAM( NON_TRANSACTED_ACCESS = OFF ) 
GO
ALTER DATABASE [WPFTask] SET TARGET_RECOVERY_TIME = 60 SECONDS 
GO
ALTER DATABASE [WPFTask] SET DELAYED_DURABILITY = DISABLED 
GO
EXEC sys.sp_db_vardecimal_storage_format N'WPFTask', N'ON'
GO
ALTER DATABASE [WPFTask] SET QUERY_STORE = OFF
GO
USE [WPFTask]
GO
/****** Object:  Table [dbo].[InventoryItems]    Script Date: 4/12/2025 10:21:33 PM ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[InventoryItems](
	[Id] [int] IDENTITY(1,1) NOT NULL,
	[Name] [nvarchar](500) NULL,
	[Category] [nvarchar](500) NULL,
	[StockQuantity] [int] NULL,
	[LastUpdated] [datetime] NOT NULL,
 CONSTRAINT [PK_Inventory] PRIMARY KEY CLUSTERED 
(
	[Id] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO
USE [master]
GO
ALTER DATABASE [WPFTask] SET  READ_WRITE 
GO
